bitfocus/companion-module-osee-gostream

src/functions/settings/feedbacks.ts
src/functions/settings/state.ts
src/functions/settings/variables.ts

connectedNdiSouce => connectedNdiSource

---

src/connection.ts

UpackDatas => UnpackDatas

---

.gitignore

Add vscode folder to .gitignore

---

package.json
src/functions/audioMixer/actions.ts
yarn.lock

Three commits
1. Fixes toggle behavior for 'Audio Mixer:Set Input Audio Enable' - Issue #47 
2. Change the action name -- this can be ignored if the third commit is accepted:
3. Completes: Combine the two Audio Enable buttons/Add second toggle option: Issue #48

'Audio Mixer Enable' issues

---

src/functions/record/actionId.ts
src/functions/record/actions.ts
src/functions/settings/actionId.ts
src/functions/settings/actions.ts

Three commits for the three issues:
1. Fixes bug reported in issue  #51 
2. Adds feature reported in issue  #52 
3. Completes code re-organization reported in issue #53

Recording issues

---

src/functions/mixEffect/actions.ts

[1.4] Update actions.ts

---

src/functions/audioMixer/feedbacks.ts
src/functions/downstreamKeyer/feedbacks.ts
src/functions/macro/feedbacks.ts
src/functions/mixEffect/feedbacks.ts
src/functions/playback/feedbacks.ts
src/functions/record/feedbacks.ts
src/functions/settings/feedbacks.ts
src/functions/streaming/feedbacks.ts
src/functions/superSource/feedbacks.ts
src/functions/upstreamKeyer/feedbacks.ts

Replace "Bank" with "Button" globally #72

[1.4] bank => button

---

src/functions/record/presets.ts
src/presets.ts

Add three presets for the previously missing Record group: record, record with timestamp, set filename w/ timestamp
This completes issue #93 Record presets are missing

Add Presets for the Record and Record-Filename actions

---

src/functions/record/presets.ts
src/presets.ts

Increase delay.
Not sure why GitHub is complaining about merges. If it's a pain, you might want to just add the zero yourself!

Ak1.4.1 record presets

---

src/functions/upstreamKeyer/feedbacks.ts

Fix improperly named variables in USK feedbacks.ts

---

src/functions/upstreamKeyer/keyTypes/pip.ts

Fixes issue #124
note that putting the word "left" "right" "top" "bottom" in the incremental input always worked.

Fix bug that prevent "Snap-to-" choices from working.

---

src/functions/playback/state.ts

Fixes , issue #141 
- correctly handle (1) no value field, (2) replacing list if value field is present.

Fix response to incoming `ActionId.PlaybackList`

---

src/functions/upstreamKeyer/presets.ts
src/upgrades/index.ts
src/upgrades/upgradeAKworkTo_v15.ts

Upgrade scripts for changes Ari Kornfeld contributed to v1.5 (since v1.4)
- Also upgrade affected presets (all in USK)
- This completes issue #122

Upgrade scripts for changes Ari Kornfeld contributed to v1.5

---

src/functions/record/presets.ts

- setters
- show status using variable in button text

Add presets for Record Quality

---

src/functions/upstreamKeyer/presets.ts

- PiP size with feedback
- Incremental and Snap-To positioning of PiP
- Incremental positioning of Key Pattern Wipe

Presets for new USK functionality

---

src/functions/superSource/variables.ts
src/functions/upstreamKeyer/variables.ts

Fixes USK fill Variables not reporting correct values issue #157

Fix prelease bug  Variables not reporting correct values

---

src/functions/mixEffect/actions.ts
src/functions/superSource/actionId.ts
src/functions/superSource/actions.ts
src/functions/upstreamKeyer/actions.ts
src/functions/upstreamKeyer/keyTypes/keyPattern.ts
src/functions/upstreamKeyer/keyTypes/pip.ts

Super Source sequences for Source1, Source2, BG, and Style
- main change is in superSource/actions.ts
- also, added the tip about using Triggers for automation to all sequences. (Can break it apart if that's a problem, but just seems simpler since it's just a text-string change.)

Super Source sequences for Source1, Source2, BG, and Style

---

src/functions/audioMixer/actions.ts
src/functions/mixEffect/actions.ts
src/functions/record/actions.ts
src/functions/superSource/actions.ts
src/functions/upstreamKeyer/actions.ts
src/functions/upstreamKeyer/keyTypes/pip.ts

Add sequences to record quality and headphones source
- files: audioMixer/actions.ts, record/actions.ts
- rename monitor source action for clarity
- also fix wording of the "Toggle" comment in relevant callbacks

Add sequences to record quality and headphones source

---

src/functions/settings/actionId.ts
src/functions/settings/state.ts
src/functions/settings/variables.ts

Add variables to settings in preparation for sequences.
- aux source, storage device
- output sources (HDMI1, HDMI2, UVC)

Add variables to settings in preparation for sequences.

---

src/functions/settings/actions.ts
src/functions/settings/feedbackId.ts
src/functions/settings/feedbacks.ts
src/functions/settings/state.ts
src/functions/settings/variables.ts

Button Brightness
- add state, action, variable for button brightness (ActionID.Panel)

Button Brightness

---

src/functions/playback/actionId.ts
src/functions/playback/actions.ts
src/functions/playback/feedbackId.ts
src/functions/playback/feedbacks.ts

Playback Next/Prev actions
- also fix wording, descriptions of some actions for consistency
- add feedback for case in which no videos are available for playback.
partially addresses issue #174

Playback Next/Prev actions
